dist: xenial
language: node_js
node_js:
  - "11"

git:
  depth: 3

env:
  - NODE_ENV=test REDIS_PORT=6379 REDIS_HOST=localhost REDIS_DB=0 MONGO_HOST=localhost MONGO_PORT=27017

services:
  - redis-server
  - mongodb

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - sleep 5
  - echo "replSet = rs" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15

cache: yarn

script:
  - yarn test:server
  - yarn test:client
