version: '3.6'
services:
  mongo:
    image: mongo:4.0.6-xenial
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exampl
    networks:
      - backendmesh

  node:
    context: ./node
    networks:
      - backendmesh

  envoy:
    context: ./envoy
    expose:
      - 80:80
      - 443:443
    networks:
      - backendmesh
    command: /usr/local/bin/envoy -c /etc/envoy.yaml
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml


  front:
    context: ./nginx
    networks:
      - backendmesh

volumes:
  data:
    driver: local

networks:
  backendmesh: {}
